source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'LOUIKit_Example', :exclusive => true do
  pod 'LOUIKit', :path => '../'
end

target 'LOUIKit_Tests', :exclusive => true do
  pod 'LOUIKit', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
